sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7

install:
  - make

script:
  - source setup-env.sh
  - python test/test.py
